version: '2'
services:
  ldap:
    image: osixia/openldap:latest
    container_name: ldap
    environment:
        - LDAP_ORGANISATION=crimsonscallion
        - LDAP_DOMAIN=crimsonscallion.com
        - LDAP_BASE_DN=dc=crimsonscallion,dc=com
    ports:
        - 389:389
        - 636:636
    volumes:
        - ldap_data:/var/lib/ldap
        - ldap_config:/etc/ldap/slapd.d
        - ldap_certs:/container/service/slapd/assets/certs

volumes:
    ldap_data:
    ldap_config:
    ldap_certs: